### ISSUE TITLE
There is no explanation for Compile

### ISSUE THREAD

**Issue by Kalle801** [Z8pn/RageSurvival#4]
Maybe a dumb question but could you please explain how to do that?

"compile" clientside code using watchify client/development/index.js -o client/index.js

Cause if im using: watchify in Node, it tells me that its wrong spelled or cant be found.

**Comment by Z8pn** [comment]
Maybe install it first

**Comment by Kalle801** [comment]
it is installed

**Comment by draobrehtom** [comment]
@Kalle801 npm install -g watchify

**Comment by Kalle801** [comment]
Okay it were not installed. Thanks for your help everyone :)

**Comment by Kalle801** [comment]
The Install is broken. No matter what i try the Compiling is broken. It starts but does nothing anymore.

**Comment by Z8pn** [comment]
Then u are either compiling wrong or installed it wrong.

Try the comment listed in the readme after installing watchify

Kalle801 <notifications@github.com> schrieb am Do., 1. Aug. 2019, 07:47:
